export enum EmployeeType {
  ADMINISTRATION = 1,
  TEACHER = 2,
  MEDIA_IT = 3,
  STAFF = 4,
}

export enum Designation {
  CHAIRMAN = 1,
  PRINCIPAL_HEAD_MUHTAMIM = 2,
  VICE_PRINCIPAL_NAIB_MUHTAMIM = 3,
  CO_ORDINATOR = 4,
  HAFEZ = 5,
  NURANI_TEACHER = 6,
  ARABIC_TEACHER = 7,
  GENERAL_TEACHER = 8,
  MEDIA_MANAGER = 9,
  IT_MANAGER = 10,
  DEVELOPER = 11,
  COOK = 12,
  GATEKEEPER = 13,
  DRIVER = 14,
  CLEANER = 15,
}
