export enum EmployeeType {
  ADMINISTRATION = 1,
  TEACHER = 2,
  MEDIA_IT = 3,
  STAFF = 4,
}

export enum Designation {
  PRINCIPAL_HEAD_MUHTAMIM = 1,
  VICE_PRINCIPAL_NAIB_MUHTAMIM = 2,
  OFFICE_ADMINISTRATOR = 3,
  ACCOUNTANT = 4,
  SUBJECT_TEACHER = 5,
  GENERAL_SUBJECTS_TEACHER = 6,
  HIFZ_TEACHER = 7,
  ASSISTANT_TEACHER = 8,
  MUALLIM = 9,
  MUALLIMA = 10,
  DEVELOPER = 11,
  MEDIA_MANAGER = 12,
  COMPUTER_OPERATOR = 13,
  PEON = 14,
  LIBRARIAN = 15,
  DRIVER = 16,
  COOK = 17,
  EDUCATION_SECRETARY = 18,
}
